Repository EPIC-model/workshop, pull requests merged in 2024-09, with the labels that each got.

#10 Fix links in pages in sites/*
  sites/01-cluster_access.md
  sites/02-setup_environment.md
  sites/03-moist_bubble.md
Labels: bug

#12 Add navigation links
  README.md
  sites/00-xwindow.md
  sites/01-cluster_access.md
  sites/02-setup_environment.md
  sites/03-moist_bubble.md
  sites/04-plotting.md
Labels: enhancement

#14 Miscellaneous changes
  input/submit-job.sh
  plotting/plot_parcel_history.py
  sites/02-setup_environment.md
  sites/03-moist_bubble.md
  sites/04-plotting.md
Labels: bug

#15 Update moist bubble section
  figures/qj3319-fig-0002-m.jpg
  input/write_moist_setup.py
  sites/03-moist_bubble.md
Labels: documentation, enhancement
